package de.dfg.oc.otc.layer1.controller;

/**
 * Exception generated by the LCS in case of errors.
 */
public class ClassifierException extends Exception {
    public ClassifierException(final String message) {
        super(message);
    }
}
