/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_unihannover_sra_otc_manager_gui_EventManager */

#ifndef _Included_de_dfg_oc_otc_manager_EventManager
#define _Included_de_dfg_oc_otc_manager_EventManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_unihannover_sra_otc_manager_gui_EventManager
 * Method:    setEvent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_dfg_oc_otc_manager_EventManager_setEvent
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
